CC_FLAGS = [
    "-std=c++20",
    "-Wall",
    "-Wpedantic",
    "-Wunused-value",
]


cc_binary(
    name = "chapter2",
    srcs = ["chapter2.cc", "testing.h"],
    copts = CC_FLAGS,
    deps = [
        "@fmt",
    ],
)